management:
  endpoint:
    health:
      show-details: always

mybatis:
  #domain对象的包
  type-aliases-package: com.xmu.discount.domain.coupon,com.xmu.discount.domain.disount

  #mapper。xml所在的位置
  mapper-locations: classpath:com.xmu.discount.mapper/*.xml
  configuration:
    #延迟加载true
    lazy-loading-enabled: true
    #立即加载false
    aggressive-lazy-loading: false
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

#redis:
#  host: localhost
#  port: 6379
#  max-wait: 30000 #连接池最大阻塞等待时间
#  max-active: 100 #连接池最大连接数
#  min-idle: 0 #连接池中的最小空闲连接
#  timeout: 3000 #连接超时


spring:
  profiles:
    active: test

#zuul:
#  routes:
#    auth:
#      path: /uaa/**
#      serviceId: auth
#    service-a:
#      path: /a/**
#      serviceId: service-a
#    service-b:
#      path: /b/**
#      serviceId: service-b
