management:
  endpoint:
    health:
      show-details: always


mybatis:
  #domain对象的包
  type-aliases-package: com.xmu.discount.domain.coupon,com.xmu.discount.domain.discount

  #mapper。xml所在的位置
  mapper-locations: classpath:com.xmu.discount/*.xml
  configuration:
    #延迟加载true
    lazy-loading-enabled: true
    #立即加载false
    aggressive-lazy-loading: false
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



spring:
  profiles:
    active: test


#zuul:
#  routes:
#    auth:
#      path: /uaa/**
#      serviceId: auth
#    service-a:
#      path: /a/**
#      serviceId: service-a
#    service-b:
#      path: /b/**
#      serviceId: service-b
